version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist jekyll-feed
  pre_build:
    commands:
      - export LC_ALL="ko_KR.UTF-8"
      - locale-gen ko_KR ko_KR.UTF-8
      - dpkg-reconfigure locales
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://blog.hankyul.io
