version: 0.1
   
phases:
  install:
    commands:
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist jekyll-feed
  pre_build:
    commands:
      - sudo apt-get update
      - sudo apt-get --assume-yes install language-pack-ko
      - locale-gen ko_KR.UTF-8
      - dpkg-reconfigure locales
      - update-locale LANG=ko_KR.UTF-8 LC_MESSAGES=POSIX
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      - jekyll build
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://blog.hankyul.io
